[local]
localhost

[local:vars]
ansible_connection=local


[appvms]

claude-code
data
debian-12-xfce-everything-dvm
default-dvm
default-mgmt-dvm
dev
llm-dvm
messenging
ocr-dvm
personal
sys-gpu-dvm
sys-vpn-proton-ch-dvm
sys-vpn-proton-fr-dvm
ubuntu-web-dolphinslabs
ubuntu-web-dvm
untrusted
youtube

[appvms:vars]
ansible_connection=qubes



[templatevms]

claude-code-template
debian-12-minimal
debian-12-xfce
debian-12-xfce-dev
debian-12-xfce-everything
debian-12-xfce-nextcloud
debian-12-xfce-proxy
debian-13-xfce
fedora-41-xfce
fedora-41-xfce-audio
fedora-41-xfce-messenging
fedora-41-xfce-net
fedora-41-xfce-proton
fedora-42-xfce
fedora-43-xfce
fedora-43-xfce-messenging
llm-template-debian-13-xfce
ocr-template-debian-13-xfce
questing-minimal
sys-gpu-template
ubuntu-web
windows_11_ltsc

[templatevms:vars]
ansible_connection=qubes



[standalonevms]

windows_11_ltsc_lightroom
windows_11_ltsc_sketchup
windows_11_ltsc_zwift

[standalonevms:vars]
ansible_connection=qubes
