all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local

    appvms:
      hosts:
        claude-code:
        data:
        debian-12-xfce-everything-dvm:
        default-dvm:
        default-mgmt-dvm:
        dev:
        firefox-app:
        llm-dvm:
        messenging:
        personal:
        untrusted:
      vars:
        ansible_connection: qubes

    templatevms:
      hosts:
        claude-code-template:
        debian-13-xfce:
        debian-13-minimal:
        fedora-43-minimal:
        fedora-43-xfce-messenging:
        firefox-template:
        llm-template-debian-13-xfce:
        questing-minimal:
      vars:
        ansible_connection: qubes

    standalonevms:
      hosts:
      vars:
        ansible_connection: qubes

    windows_vms:
      hosts:
      vars:
        ansible_connection: qubes

    disp_vms:
      hosts:
        llm-disp:
      vars:
        ansible_connection: qubes
