---
- name: Update APT
  ansible.builtin.apt:
    upgrade: "dist"
    update_cache: true
- name: Install additional packages
  ansible.builtin.apt:
    name:
    - python3-full
    - python3-pip
    - python3-venv
    state: present
