---
#
# Template
#
- hosts: local
  connection: local
  vars_files:
    - vars/firefox.yml
  tasks:
    - include_tasks: tasks/clone_template.yml
      vars:
        clone_src: "{{ firefox_base_template }}"
        clone_dest: "{{ host_firefox_template }}"

- hosts: "{{ host_firefox_template | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/firefox.yml
  roles:
    - role: base_packages
    - role: firefox

- hosts: local
  connection: local
  vars_files:
    - vars/firefox.yml
  tasks:
    - name: Shutdown the FIREFOX Template
      qubesos:
        guest: "{{ host_firefox_template }}"
        state: shutdown

#
# AppVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/firefox.yml
  tasks:
    - name: Check if AppVM exists
      shell: "qvm-ls --raw-data --fields name | grep -w {{ host_firefox_app }}"
      register: app_check
      failed_when: false
      changed_when: false
    - name: Create AppVM
      command: qvm-create --class AppVM --label blue --template {{ host_firefox_template }} {{ host_firefox_app }}
      when: app_check.rc != 0
    - name: Set APP network
      command: qvm-prefs {{ host_firefox_app }} netvm {{ netvm_default }}
    - include_role:
        name: set_prefs
      vars:
        target_vm: "{{ host_firefox_app }}"
        vm_qrexec_timeout: "{{ qrexec_timeout_default }}"
