---
#
# Template
#
- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - include_tasks: tasks/qubes_clone_template.yml
      vars:
        clone_src: "{{ llm_base_template }}"
        clone_dest: "{{ llm_host_template }}"

- hosts: "{{ llm_host_template | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/llm.yml
  roles:
    - role: llm_template

- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Shutdown the LLM Template
      qubesos:
        guest: "{{ llm_host_template }}"
        state: shutdown
    - name: Remove the network
      command: qvm-prefs {{ llm_host_template }} netvm ''

#
# DVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Check if DVM exists
      shell: "qvm-ls --raw-data --fields name | grep -w {{ llm_host_dvm }}"
      register: llm_dvm_check
      failed_when: false
      changed_when: false
    - name: Create DVM
      command: qvm-create --class AppVM --label blue --template {{ llm_host_template }} {{ llm_host_dvm }}
      when: llm_dvm_check.rc != 0
    - name: Set DVM label
      command: qvm-prefs {{ llm_host_dvm }} label blue
    - name: Set DVM network
      command: qvm-prefs {{ llm_host_dvm }} netvm {{ netvm_default }}
    - name: Set as DispVM template
      command: qvm-prefs {{ llm_host_dvm }} template_for_dispvms true
    - name: Resize private volume
      command: qvm-volume resize {{ llm_host_dvm }}:private 100GB
      when: llm_dvm_check.rc != 0
    - include_role:
        name: qubes_set_timeout
      vars:
        target_vm: "{{ llm_host_dvm }}"

- hosts: "{{ llm_host_dvm | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/llm.yml
  roles:
    - role: llm_dvm_1

- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Shutdown the LLM DVM
      qubesos:
        guest: "{{ llm_host_dvm }}"
        state: shutdown

- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Start the LLM DVM
      qubesos:
        guest: "{{ llm_host_dvm }}"
        state: running

- hosts: "{{ llm_host_dvm | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/llm.yml
  roles:
    - role: llm_dvm_2

- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Shutdown the LLM DVM
      qubesos:
        guest: "{{ llm_host_dvm }}"
        state: shutdown

#
# DispVM
#
- hosts: local
  connection: local
  vars_files:
    - vars/llm.yml
    - vars/sys_gpu.yml
  tasks:
    - name: Check if DispVM exists
      shell: "qvm-ls --raw-data --fields name | grep -w {{ llm_dispvm }}"
      register: llm_dispvm_check
      failed_when: false
      changed_when: false
    - name: Create DispVM
      command: qvm-create --class DispVM --label red --template {{ llm_host_dvm }} {{ llm_dispvm }}
      when: llm_dispvm_check.rc != 0
    - name: Set default DVM
      command: qvm-prefs {{ llm_dispvm }} default_dispvm {{ llm_host_dvm }}
    - name: Set label
      command: qvm-prefs {{ llm_dispvm }} label red
    - name: Set HVM mode
      command: qvm-prefs {{ llm_dispvm }} virt_mode hvm
    - name: Set network
      command: qvm-prefs {{ llm_dispvm }} netvm {{ netvm_default }}
    - name: Set VCPU count
      command: qvm-prefs {{ llm_dispvm }} vcpus 10
    - name: Set memory
      command: qvm-prefs {{ llm_dispvm }} memory {{ llm_memory }}
    - name: Disable memory balancing
      command: qvm-prefs {{ llm_dispvm }} maxmem 0
    - include_role:
        name: qubes_set_timeout
      vars:
        target_vm: "{{ llm_dispvm }}"
    - name: Attach GPU VGA
      command: qvm-pci attach {{ llm_dispvm }} dom0:{{ gpu_pci_id_vga }} --persistent
    - name: Attach GPU Audio
      command: qvm-pci attach {{ llm_dispvm }} dom0:{{ gpu_pci_id_audio }} --persistent

#
# Networking
#
- hosts: local
  become: yes
  connection: local
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Ensure network policy file exists
      file:
        path: "{{ networking_policy_file }}"
        owner: root
        group: qubes
        mode: '0664'
        state: touch
    - name: Set network policy for LLM
      lineinfile:
        path: "{{ networking_policy_file }}"
        regexp: "{{ llm_tcp_port }}.*{{ llm_dispvm }}"
        line: "qubes.ConnectTCP +{{ llm_tcp_port }} {{ llm_host_claude_code }} @default allow target={{ llm_dispvm }}"
        state: present

- hosts: "{{ llm_host_claude_code | default([]) }}"
  become: yes
  connection: qubes
  vars_files:
    - vars/llm.yml
  tasks:
    - name: Set connection to LLM at startup
      lineinfile:
        path: "{{ rc_local }}"
        regexp: "qvm-connect-tcp.*{{ llm_tcp_port }}"
        line: "qvm-connect-tcp {{ llm_tcp_port }}:@default:{{ llm_tcp_port }}"
        state: present
