---
- name: Install base packages (Debian)
  apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install base packages (RedHat)
  dnf:
    name: "{{ base_packages }}"
    state: present
  become: yes
  when: ansible_os_family == 'RedHat'
